# Generated by Django 4.2 on 2023-05-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[

                ('username', models.CharField(max_length=18)),
                ('password', models.CharField(max_length=24)),
                ('birthdate', models.DateField()),

            ],
        ),
    ]
