# Generated by Django 4.2 on 2023-05-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='ID',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
