# Generated by Django 4.2 on 2023-05-20 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T1', '0002_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='ID',
            field=models.IntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=24, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
