# Generated by Django 4.2 on 2023-05-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('T1', '0003_alter_register_id_alter_register_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='ID',
            new_name='internationalID',
        ),
    ]
