# Generated by Django 4.2 on 2023-05-20 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T1', '0004_rename_id_register_internationalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='internationalID',
            field=models.IntegerField(primary_key=True ,validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
