# Generated by Django 4.2 on 2023-06-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('T1', '0006_register_id_alter_register_internationalid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
